# Generated by Django 5.1.1 on 2024-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('aun', models.IntegerField()),
                ('county', models.TextField(max_length=1000)),
                ('salary', models.IntegerField()),
                ('name', models.TextField(max_length=1000)),
            ],
        ),
    ]
