# Generated by Django 5.1.1 on 2024-10-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_district_districtenrollment_districtfiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('School', models.CharField(max_length=100)),
                ('enrollmentnum', models.IntegerField()),
                ('years', models.CharField(max_length=100)),
            ],
        ),
    ]
