# Generated by Django 5.1.1 on 2024-12-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_district_district_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='career_and_technical_center_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='career_and_technical_center_website',
        ),
        migrations.RemoveField(
            model_name='district',
            name='intermediate_unit_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='intermediate_unit_website',
        ),
    ]
