# Generated by Django 5.1.1 on 2024-12-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_districtkeystonestats_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtkeystone',
            name='numbers_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districtkeystone',
            name='percent_advanced',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='districtkeystone',
            name='percent_basic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='districtkeystone',
            name='percent_below_basic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='districtkeystone',
            name='percent_proficient',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='group',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='subject',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='year',
            field=models.IntegerField(default='Null'),
        ),
        migrations.DeleteModel(
            name='districtKeystoneStats',
        ),
    ]
