# Generated by Django 5.1.1 on 2024-12-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_districtkeystone_numbers_scored_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_address_state',
        ),
    ]
