# Generated by Django 5.1.1 on 2024-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_district_district_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtkeystone',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
