# Generated by Django 5.1.2 on 2024-12-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_districtkeystone_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='dropouts_female',
        ),
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='dropouts_male',
        ),
    ]
