# Generated by Django 5.1.2 on 2024-12-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_schoolenrollment_dropouts_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='foster_care_percent',
        ),
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='low_income_percent',
        ),
    ]
