# Generated by Django 5.1.1 on 2024-12-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_districtpssa_district_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='districtFiscal',
            fields=[
                ('fiscal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('federal_revenue', models.FloatField()),
                ('local_revenue', models.FloatField()),
                ('state_revenue', models.FloatField()),
                ('total_expenditures', models.FloatField()),
                ('total_revenue', models.FloatField()),
                ('year', models.IntegerField()),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.district')),
            ],
        ),
        migrations.DeleteModel(
            name='districtFiscalStats',
        ),
    ]
