# Generated by Django 5.1.1 on 2024-12-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_districtfiscal_delete_districtfiscalstats'),
        ('pages', '0014_remove_schoolenrollment_foster_care_percent_and_more'),
    ]

    operations = [
    ]
