# Generated by Django 5.1.1 on 2024-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_merge_20241209_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpssa',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='schoolpssastats',
            name='pssa_id',
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='group',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='numbers_scored',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='percent_advanced',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='percent_basic',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='percent_below_basic',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolkeystone',
            name='percent_proficient',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='schoolkeystone',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='SchoolKeystoneStats',
        ),
        migrations.DeleteModel(
            name='SchoolPSSA',
        ),
        migrations.DeleteModel(
            name='SchoolPSSAStats',
        ),
    ]
