# Generated by Django 5.1.2 on 2024-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_schoolpssa_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
