# Generated by Django 5.1.1 on 2024-12-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfiscal',
            name='local_personnel',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolfiscal',
            name='state_non_personnel',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='schoolfiscal',
            name='state_personnel',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='schoolfiscal',
            name='federal_non_personnel',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='schoolfiscal',
            name='federal_personnel',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='schoolfiscal',
            name='local_non_personnel',
            field=models.FloatField(default=-1),
        ),
    ]
