# Generated by Django 5.1.1 on 2024-12-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_schoolfiscal_local_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolfiscal',
            name='year',
            field=models.IntegerField(default=-1),
        ),
    ]
