# Generated by Django 5.1.1 on 2024-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_schoolfiscal_id_alter_schoolfiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='federal_revenue',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='local_revenue',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='state_revenue',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='total_expenditures',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='total_revenue',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtfiscal',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='group',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='numbers_scored',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='percent_advanced',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='percent_basic',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='percent_below_basic',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='percent_proficient',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='districtkeystone',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
